name: Add Tag

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Get package.json version"
        id: set_var
        run: |
          content=`cat package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - name: "Show version"
        run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
      - name: "Create tag"
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{fromJson(steps.set_var.outputs.packageJson).version}}
          tag_exists_error: false
          force_push_tag: true
          message: "Latest release: ${{ github.event.head_commit.message }}"
